Sketch index page
oscarjosecostero/Easyrent pull request #11
Opened 2017-08-24 17:55 UTC by oscarjosecostero

#3 
Installed bourbon
Installed Slim
Installed Bourbon
Index page basically sketched

2017-08-24 19:40 UTC, OscarlynCostero requested changes
All good! There are a few thing to change but we can change most of it on the run. 

However, I left you two comments.

2017-08-24 19:40 UTC, OscarlynCostero commented on app/views/layouts/application.html.erb
>      <title>Easyrent</title>
Convert this file to slim.

2017-08-24 19:40 UTC, OscarlynCostero commented on .gitignore
> +.notes.txt
Please remove this line and add this.
```
/public
/vendor
Gemfile.lock
```

2017-08-25 01:08 UTC, gbrlmrllo approved these changes
Good job 👍 , I made some minor changes, so I could merge.

2017-08-25 01:09 UTC, merged