install and configure devise
oscarjosecostero/Easyrent pull request #2
Opened 2017-08-10 15:36 UTC by oscarjosecostero

2017-08-12 17:44 UTC, gbrlmrllo requested changes

2017-08-12 17:44 UTC, gbrlmrllo commented on app/assets/javascripts/home.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
Delete this file.

2017-08-12 17:44 UTC, gbrlmrllo commented on app/assets/stylesheets/home.scss
> +// Place all the styles related to the Home controller here.
Delete this file.

2017-08-12 17:44 UTC, gbrlmrllo commented on app/controllers/users/confirmations_controller.rb
> +class Users::ConfirmationsController < Devise::ConfirmationsController
Delete this file.

2017-08-12 17:44 UTC, gbrlmrllo commented on app/controllers/users/omniauth_callbacks_controller.rb
> +class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
Delete this file.

2017-08-12 17:44 UTC, gbrlmrllo commented on app/controllers/users/passwords_controller.rb
> +class Users::PasswordsController < Devise::PasswordsController
Delete this file.

2017-08-12 17:44 UTC, gbrlmrllo commented on app/controllers/users/sessions_controller.rb
> +class Users::SessionsController < Devise::SessionsController
Delete this file

2017-08-12 17:44 UTC, gbrlmrllo commented on app/controllers/users/unlocks_controller.rb
> +class Users::UnlocksController < Devise::UnlocksController
Delete this file.

2017-08-12 17:44 UTC, gbrlmrllo commented on config/routes.rb
>  Rails.application.routes.draw do
There are several blank lines.

2017-08-12 17:44 UTC, gbrlmrllo commented on test/mailers/previews/user_notifier_mailer_preview.rb
> +class UserNotifierMailerPreview < ActionMailer::Preview
Fix identation, must be two spaces.

2017-08-12 18:15 UTC, gbrlmrllo requested changes

2017-08-12 18:15 UTC, gbrlmrllo commented on config/environment.rb
> +  :user_name => 'gbrlmrllo',
Use this syntax better:

```user_name: 'gbrlmrllo'```

2017-08-12 18:15 UTC, gbrlmrllo commented on config/environment.rb
> +  :password => 'easyrent2017',
We must also use environment variables for some data, we can not make [hard-code](https://es.wikipedia.org/wiki/Hard_code), for security reasons and good practices.

2017-08-14 14:10 UTC, oscarjosecostero commented on test/mailers/previews/user_notifier_mailer_preview.rb
> +class UserNotifierMailerPreview < ActionMailer::Preview
Identation Fixed.
This code is for testing and design purposes only. We can preview the email to be sent, without actually send it, just by following this link: http://localhost:3000/rails/mailers/user_notifier_mailer. I used it to make sure the code was correct and that it was generating the email. We can delete it now.

2017-08-14 16:41 UTC, gbrlmrllo requested changes

2017-08-14 16:41 UTC, gbrlmrllo commented on test/mailers/previews/user_notifier_mailer_preview.rb
> +class UserNotifierMailerPreview < ActionMailer::Preview
I didn't know that, cool!

btw, the indentation is still not correct, it should be two spaces instead of two tabs.

2017-08-14 17:59 UTC, oscarjosecostero commented on test/mailers/previews/user_notifier_mailer_preview.rb
> +class UserNotifierMailerPreview < ActionMailer::Preview
I had made the changes. but i think i uploaded before saving that. It appeared when i used "git status". Sorry, rookie mistake

2017-08-14 18:10 UTC, gbrlmrllo approved these changes

2017-08-14 18:12 UTC, merged